spring.application.name=moneyservices

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/moneyservice_db
spring.datasource.username=postgres
spring.datasource.password=]UP9T.5-9+rO

server.port=8095

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

